name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2021-01-13"
machine_id: 1

auth:
  jwt_expire: 800

mysql:
  host: localhost
  port: 3306
  user: "root"
  password: "12345678"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100
log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
